import type { Metadata } from "next";
import { FloatingNav } from '@/components/ui/floating-navbar'
import { Suspense } from 'react';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <body>
        <Suspense fallback={<div>Loading...</div>}>
          <FloatingNav />
        </Suspense>
        {children}
      </body>
  );
} 